### ISSUE TITLE
Current tab doesn't show Custom Lists

### ISSUE THREAD

**Issue by yash-278** [lotusgate/otraku#66] opened 2022-12-17 10:08 UTC
With the new Update the current tab, it's not showing anything on my lists as of now. I need to expand to go to Lists.

Edit : (Not sure why I can't attach a Screenshot on GitHub mobile 😂). But I don't have any default lists given by Anilist, all my Lists are custom. Probably that's the issue.

**Comment by lotusgate** [comment] 2022-12-17 10:21
Yes, the collection preview only supports getting your watching/rewatching list and gathering data from there. If you can't use it, you can turn off the preview from the first tab of settings -> collection previews.
The problem is that I will otherwise have to fetch all your custom lists and traverse them to gather your current entries, but the whole point of the preview is to quickly load only the most important stuff.
I'm closing this, as it's not a bug, but you can still ask questions, of course.

**Closed by lotusgate** 2022-12-17 10:21 UTC
